#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marketing
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="sab-db")]
	public partial class MarketingDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertcampaign(campaign instance);
    partial void Updatecampaign(campaign instance);
    partial void Deletecampaign(campaign instance);
    partial void Insertbrand(brand instance);
    partial void Updatebrand(brand instance);
    partial void Deletebrand(brand instance);
    partial void Insertcategory(category instance);
    partial void Updatecategory(category instance);
    partial void Deletecategory(category instance);
    partial void Insertcountry(country instance);
    partial void Updatecountry(country instance);
    partial void Deletecountry(country instance);
    partial void Insertterritory(territory instance);
    partial void Updateterritory(territory instance);
    partial void Deleteterritory(territory instance);
    partial void Insertusage(usage instance);
    partial void Updateusage(usage instance);
    partial void Deleteusage(usage instance);
    partial void Insertusage_type(usage_type instance);
    partial void Updateusage_type(usage_type instance);
    partial void Deleteusage_type(usage_type instance);
    partial void Insertcampaign_type(campaign_type instance);
    partial void Updatecampaign_type(campaign_type instance);
    partial void Deletecampaign_type(campaign_type instance);
    #endregion
		
		public MarketingDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["sab_dbConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MarketingDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MarketingDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MarketingDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MarketingDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<campaign> campaigns
		{
			get
			{
				return this.GetTable<campaign>();
			}
		}
		
		public System.Data.Linq.Table<brand> brands
		{
			get
			{
				return this.GetTable<brand>();
			}
		}
		
		public System.Data.Linq.Table<campaign_document> campaign_documents
		{
			get
			{
				return this.GetTable<campaign_document>();
			}
		}
		
		public System.Data.Linq.Table<category> categories
		{
			get
			{
				return this.GetTable<category>();
			}
		}
		
		public System.Data.Linq.Table<country> countries
		{
			get
			{
				return this.GetTable<country>();
			}
		}
		
		public System.Data.Linq.Table<territory> territories
		{
			get
			{
				return this.GetTable<territory>();
			}
		}
		
		public System.Data.Linq.Table<usage> usages
		{
			get
			{
				return this.GetTable<usage>();
			}
		}
		
		public System.Data.Linq.Table<usage_type> usage_types
		{
			get
			{
				return this.GetTable<usage_type>();
			}
		}
		
		public System.Data.Linq.Table<campaign_type> campaign_types
		{
			get
			{
				return this.GetTable<campaign_type>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usage_report")]
		public ISingleResult<usage_reportResult> usage_report([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> start, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> end)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), start, end);
			return ((ISingleResult<usage_reportResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.statistics_brands_report")]
		public ISingleResult<statistics_brands_reportResult> statistics_brands_report([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> start, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> end)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), start, end);
			return ((ISingleResult<statistics_brands_reportResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.statistics_campaign_types_report")]
		public ISingleResult<statistics_campaign_types_reportResult> statistics_campaign_types_report([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> start, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> end)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), start, end);
			return ((ISingleResult<statistics_campaign_types_reportResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.statistics_categories_report")]
		public ISingleResult<statistics_categories_reportResult> statistics_categories_report([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> start, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> end)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), start, end);
			return ((ISingleResult<statistics_categories_reportResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.statistics_countries_report")]
		public ISingleResult<statistics_countries_reportResult> statistics_countries_report([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> start, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> end)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), start, end);
			return ((ISingleResult<statistics_countries_reportResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.statistics_territories_report")]
		public ISingleResult<statistics_territories_reportResult> statistics_territories_report([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> start, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> end)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), start, end);
			return ((ISingleResult<statistics_territories_reportResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.upload_report")]
		public ISingleResult<upload_reportResult> upload_report([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> start, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> end)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), start, end);
			return ((ISingleResult<upload_reportResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.campaign")]
	public partial class campaign : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _campaign_id;
		
		private int _category_id;
		
		private int _territory_id;
		
		private int _campaign_type_id;
		
		private int _country_id;
		
		private int _brand_id;
		
		private string _title;
		
		private string _username;
		
		private System.Nullable<System.DateTime> _create_ts;
		
		private System.Nullable<System.DateTime> _update_ts;
		
		private EntityRef<brand> _brand;
		
		private EntityRef<category> _category;
		
		private EntityRef<country> _country;
		
		private EntityRef<territory> _territory;
		
		private EntityRef<campaign_type> _campaign_type;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncampaign_idChanging(int value);
    partial void Oncampaign_idChanged();
    partial void Oncategory_idChanging(int value);
    partial void Oncategory_idChanged();
    partial void Onterritory_idChanging(int value);
    partial void Onterritory_idChanged();
    partial void Oncampaign_type_idChanging(int value);
    partial void Oncampaign_type_idChanged();
    partial void Oncountry_idChanging(int value);
    partial void Oncountry_idChanged();
    partial void Onbrand_idChanging(int value);
    partial void Onbrand_idChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void Oncreate_tsChanging(System.Nullable<System.DateTime> value);
    partial void Oncreate_tsChanged();
    partial void Onupdate_tsChanging(System.Nullable<System.DateTime> value);
    partial void Onupdate_tsChanged();
    #endregion
		
		public campaign()
		{
			this._brand = default(EntityRef<brand>);
			this._category = default(EntityRef<category>);
			this._country = default(EntityRef<country>);
			this._territory = default(EntityRef<territory>);
			this._campaign_type = default(EntityRef<campaign_type>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_campaign_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int campaign_id
		{
			get
			{
				return this._campaign_id;
			}
			set
			{
				if ((this._campaign_id != value))
				{
					this.Oncampaign_idChanging(value);
					this.SendPropertyChanging();
					this._campaign_id = value;
					this.SendPropertyChanged("campaign_id");
					this.Oncampaign_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category_id", DbType="Int NOT NULL")]
		public int category_id
		{
			get
			{
				return this._category_id;
			}
			set
			{
				if ((this._category_id != value))
				{
					if (this._category.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncategory_idChanging(value);
					this.SendPropertyChanging();
					this._category_id = value;
					this.SendPropertyChanged("category_id");
					this.Oncategory_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_territory_id", DbType="Int NOT NULL")]
		public int territory_id
		{
			get
			{
				return this._territory_id;
			}
			set
			{
				if ((this._territory_id != value))
				{
					if (this._territory.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onterritory_idChanging(value);
					this.SendPropertyChanging();
					this._territory_id = value;
					this.SendPropertyChanged("territory_id");
					this.Onterritory_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_campaign_type_id", DbType="Int NOT NULL")]
		public int campaign_type_id
		{
			get
			{
				return this._campaign_type_id;
			}
			set
			{
				if ((this._campaign_type_id != value))
				{
					if (this._campaign_type.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncampaign_type_idChanging(value);
					this.SendPropertyChanging();
					this._campaign_type_id = value;
					this.SendPropertyChanged("campaign_type_id");
					this.Oncampaign_type_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_country_id", DbType="Int NOT NULL")]
		public int country_id
		{
			get
			{
				return this._country_id;
			}
			set
			{
				if ((this._country_id != value))
				{
					if (this._country.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncountry_idChanging(value);
					this.SendPropertyChanging();
					this._country_id = value;
					this.SendPropertyChanged("country_id");
					this.Oncountry_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_brand_id", DbType="Int NOT NULL")]
		public int brand_id
		{
			get
			{
				return this._brand_id;
			}
			set
			{
				if ((this._brand_id != value))
				{
					if (this._brand.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onbrand_idChanging(value);
					this.SendPropertyChanging();
					this._brand_id = value;
					this.SendPropertyChanged("brand_id");
					this.Onbrand_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_ts", DbType="DateTime")]
		public System.Nullable<System.DateTime> create_ts
		{
			get
			{
				return this._create_ts;
			}
			set
			{
				if ((this._create_ts != value))
				{
					this.Oncreate_tsChanging(value);
					this.SendPropertyChanging();
					this._create_ts = value;
					this.SendPropertyChanged("create_ts");
					this.Oncreate_tsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_update_ts", DbType="DateTime")]
		public System.Nullable<System.DateTime> update_ts
		{
			get
			{
				return this._update_ts;
			}
			set
			{
				if ((this._update_ts != value))
				{
					this.Onupdate_tsChanging(value);
					this.SendPropertyChanging();
					this._update_ts = value;
					this.SendPropertyChanged("update_ts");
					this.Onupdate_tsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="brand_campaign", Storage="_brand", ThisKey="brand_id", OtherKey="brand_id", IsForeignKey=true)]
		public brand brand
		{
			get
			{
				return this._brand.Entity;
			}
			set
			{
				brand previousValue = this._brand.Entity;
				if (((previousValue != value) 
							|| (this._brand.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._brand.Entity = null;
						previousValue.campaigns.Remove(this);
					}
					this._brand.Entity = value;
					if ((value != null))
					{
						value.campaigns.Add(this);
						this._brand_id = value.brand_id;
					}
					else
					{
						this._brand_id = default(int);
					}
					this.SendPropertyChanged("brand");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="category_campaign", Storage="_category", ThisKey="category_id", OtherKey="category_id", IsForeignKey=true)]
		public category category
		{
			get
			{
				return this._category.Entity;
			}
			set
			{
				category previousValue = this._category.Entity;
				if (((previousValue != value) 
							|| (this._category.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._category.Entity = null;
						previousValue.campaigns.Remove(this);
					}
					this._category.Entity = value;
					if ((value != null))
					{
						value.campaigns.Add(this);
						this._category_id = value.category_id;
					}
					else
					{
						this._category_id = default(int);
					}
					this.SendPropertyChanged("category");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="country_campaign", Storage="_country", ThisKey="country_id", OtherKey="country_id", IsForeignKey=true)]
		public country country
		{
			get
			{
				return this._country.Entity;
			}
			set
			{
				country previousValue = this._country.Entity;
				if (((previousValue != value) 
							|| (this._country.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._country.Entity = null;
						previousValue.campaigns.Remove(this);
					}
					this._country.Entity = value;
					if ((value != null))
					{
						value.campaigns.Add(this);
						this._country_id = value.country_id;
					}
					else
					{
						this._country_id = default(int);
					}
					this.SendPropertyChanged("country");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="territory_campaign", Storage="_territory", ThisKey="territory_id", OtherKey="territory_id", IsForeignKey=true)]
		public territory territory
		{
			get
			{
				return this._territory.Entity;
			}
			set
			{
				territory previousValue = this._territory.Entity;
				if (((previousValue != value) 
							|| (this._territory.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._territory.Entity = null;
						previousValue.campaigns.Remove(this);
					}
					this._territory.Entity = value;
					if ((value != null))
					{
						value.campaigns.Add(this);
						this._territory_id = value.territory_id;
					}
					else
					{
						this._territory_id = default(int);
					}
					this.SendPropertyChanged("territory");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="campaign_type_campaign", Storage="_campaign_type", ThisKey="campaign_type_id", OtherKey="campaign_type_id", IsForeignKey=true)]
		public campaign_type campaign_type
		{
			get
			{
				return this._campaign_type.Entity;
			}
			set
			{
				campaign_type previousValue = this._campaign_type.Entity;
				if (((previousValue != value) 
							|| (this._campaign_type.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._campaign_type.Entity = null;
						previousValue.campaigns.Remove(this);
					}
					this._campaign_type.Entity = value;
					if ((value != null))
					{
						value.campaigns.Add(this);
						this._campaign_type_id = value.campaign_type_id;
					}
					else
					{
						this._campaign_type_id = default(int);
					}
					this.SendPropertyChanged("campaign_type");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.brand")]
	public partial class brand : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _brand_id;
		
		private string _brand_description;
		
		private System.Nullable<bool> _active;
		
		private System.Nullable<System.DateTime> _create_ts;
		
		private System.Nullable<System.DateTime> _update_ts;
		
		private EntitySet<campaign> _campaigns;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onbrand_idChanging(int value);
    partial void Onbrand_idChanged();
    partial void Onbrand_descriptionChanging(string value);
    partial void Onbrand_descriptionChanged();
    partial void OnactiveChanging(System.Nullable<bool> value);
    partial void OnactiveChanged();
    partial void Oncreate_tsChanging(System.Nullable<System.DateTime> value);
    partial void Oncreate_tsChanged();
    partial void Onupdate_tsChanging(System.Nullable<System.DateTime> value);
    partial void Onupdate_tsChanged();
    #endregion
		
		public brand()
		{
			this._campaigns = new EntitySet<campaign>(new Action<campaign>(this.attach_campaigns), new Action<campaign>(this.detach_campaigns));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_brand_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int brand_id
		{
			get
			{
				return this._brand_id;
			}
			set
			{
				if ((this._brand_id != value))
				{
					this.Onbrand_idChanging(value);
					this.SendPropertyChanging();
					this._brand_id = value;
					this.SendPropertyChanged("brand_id");
					this.Onbrand_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_brand_description", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string brand_description
		{
			get
			{
				return this._brand_description;
			}
			set
			{
				if ((this._brand_description != value))
				{
					this.Onbrand_descriptionChanging(value);
					this.SendPropertyChanging();
					this._brand_description = value;
					this.SendPropertyChanged("brand_description");
					this.Onbrand_descriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_active", DbType="Bit")]
		public System.Nullable<bool> active
		{
			get
			{
				return this._active;
			}
			set
			{
				if ((this._active != value))
				{
					this.OnactiveChanging(value);
					this.SendPropertyChanging();
					this._active = value;
					this.SendPropertyChanged("active");
					this.OnactiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_ts", DbType="DateTime")]
		public System.Nullable<System.DateTime> create_ts
		{
			get
			{
				return this._create_ts;
			}
			set
			{
				if ((this._create_ts != value))
				{
					this.Oncreate_tsChanging(value);
					this.SendPropertyChanging();
					this._create_ts = value;
					this.SendPropertyChanged("create_ts");
					this.Oncreate_tsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_update_ts", DbType="DateTime")]
		public System.Nullable<System.DateTime> update_ts
		{
			get
			{
				return this._update_ts;
			}
			set
			{
				if ((this._update_ts != value))
				{
					this.Onupdate_tsChanging(value);
					this.SendPropertyChanging();
					this._update_ts = value;
					this.SendPropertyChanged("update_ts");
					this.Onupdate_tsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="brand_campaign", Storage="_campaigns", ThisKey="brand_id", OtherKey="brand_id")]
		public EntitySet<campaign> campaigns
		{
			get
			{
				return this._campaigns;
			}
			set
			{
				this._campaigns.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_campaigns(campaign entity)
		{
			this.SendPropertyChanging();
			entity.brand = this;
		}
		
		private void detach_campaigns(campaign entity)
		{
			this.SendPropertyChanging();
			entity.brand = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.campaign_document")]
	public partial class campaign_document
	{
		
		private System.Guid _id;
		
		private System.Data.Linq.Binary _document;
		
		private System.Nullable<int> _content_length;
		
		private string _content_type;
		
		private string _file_name;
		
		private int _campaign_id;
		
		public campaign_document()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_document", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary document
		{
			get
			{
				return this._document;
			}
			set
			{
				if ((this._document != value))
				{
					this._document = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_content_length", DbType="Int")]
		public System.Nullable<int> content_length
		{
			get
			{
				return this._content_length;
			}
			set
			{
				if ((this._content_length != value))
				{
					this._content_length = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_content_type", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string content_type
		{
			get
			{
				return this._content_type;
			}
			set
			{
				if ((this._content_type != value))
				{
					this._content_type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_file_name", DbType="VarChar(512) NOT NULL", CanBeNull=false)]
		public string file_name
		{
			get
			{
				return this._file_name;
			}
			set
			{
				if ((this._file_name != value))
				{
					this._file_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_campaign_id", DbType="Int NOT NULL")]
		public int campaign_id
		{
			get
			{
				return this._campaign_id;
			}
			set
			{
				if ((this._campaign_id != value))
				{
					this._campaign_id = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.category")]
	public partial class category : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _category_id;
		
		private string _category_description;
		
		private System.Nullable<bool> _active;
		
		private System.Nullable<System.DateTime> _create_ts;
		
		private System.Nullable<System.DateTime> _update_ts;
		
		private EntitySet<campaign> _campaigns;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncategory_idChanging(int value);
    partial void Oncategory_idChanged();
    partial void Oncategory_descriptionChanging(string value);
    partial void Oncategory_descriptionChanged();
    partial void OnactiveChanging(System.Nullable<bool> value);
    partial void OnactiveChanged();
    partial void Oncreate_tsChanging(System.Nullable<System.DateTime> value);
    partial void Oncreate_tsChanged();
    partial void Onupdate_tsChanging(System.Nullable<System.DateTime> value);
    partial void Onupdate_tsChanged();
    #endregion
		
		public category()
		{
			this._campaigns = new EntitySet<campaign>(new Action<campaign>(this.attach_campaigns), new Action<campaign>(this.detach_campaigns));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int category_id
		{
			get
			{
				return this._category_id;
			}
			set
			{
				if ((this._category_id != value))
				{
					this.Oncategory_idChanging(value);
					this.SendPropertyChanging();
					this._category_id = value;
					this.SendPropertyChanged("category_id");
					this.Oncategory_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category_description", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string category_description
		{
			get
			{
				return this._category_description;
			}
			set
			{
				if ((this._category_description != value))
				{
					this.Oncategory_descriptionChanging(value);
					this.SendPropertyChanging();
					this._category_description = value;
					this.SendPropertyChanged("category_description");
					this.Oncategory_descriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_active", DbType="Bit")]
		public System.Nullable<bool> active
		{
			get
			{
				return this._active;
			}
			set
			{
				if ((this._active != value))
				{
					this.OnactiveChanging(value);
					this.SendPropertyChanging();
					this._active = value;
					this.SendPropertyChanged("active");
					this.OnactiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_ts", DbType="DateTime")]
		public System.Nullable<System.DateTime> create_ts
		{
			get
			{
				return this._create_ts;
			}
			set
			{
				if ((this._create_ts != value))
				{
					this.Oncreate_tsChanging(value);
					this.SendPropertyChanging();
					this._create_ts = value;
					this.SendPropertyChanged("create_ts");
					this.Oncreate_tsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_update_ts", DbType="DateTime")]
		public System.Nullable<System.DateTime> update_ts
		{
			get
			{
				return this._update_ts;
			}
			set
			{
				if ((this._update_ts != value))
				{
					this.Onupdate_tsChanging(value);
					this.SendPropertyChanging();
					this._update_ts = value;
					this.SendPropertyChanged("update_ts");
					this.Onupdate_tsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="category_campaign", Storage="_campaigns", ThisKey="category_id", OtherKey="category_id")]
		public EntitySet<campaign> campaigns
		{
			get
			{
				return this._campaigns;
			}
			set
			{
				this._campaigns.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_campaigns(campaign entity)
		{
			this.SendPropertyChanging();
			entity.category = this;
		}
		
		private void detach_campaigns(campaign entity)
		{
			this.SendPropertyChanging();
			entity.category = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.country")]
	public partial class country : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _country_id;
		
		private string _country_description;
		
		private System.Nullable<bool> _active;
		
		private System.Nullable<System.DateTime> _create_ts;
		
		private System.Nullable<System.DateTime> _update_ts;
		
		private EntitySet<campaign> _campaigns;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncountry_idChanging(int value);
    partial void Oncountry_idChanged();
    partial void Oncountry_descriptionChanging(string value);
    partial void Oncountry_descriptionChanged();
    partial void OnactiveChanging(System.Nullable<bool> value);
    partial void OnactiveChanged();
    partial void Oncreate_tsChanging(System.Nullable<System.DateTime> value);
    partial void Oncreate_tsChanged();
    partial void Onupdate_tsChanging(System.Nullable<System.DateTime> value);
    partial void Onupdate_tsChanged();
    #endregion
		
		public country()
		{
			this._campaigns = new EntitySet<campaign>(new Action<campaign>(this.attach_campaigns), new Action<campaign>(this.detach_campaigns));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_country_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int country_id
		{
			get
			{
				return this._country_id;
			}
			set
			{
				if ((this._country_id != value))
				{
					this.Oncountry_idChanging(value);
					this.SendPropertyChanging();
					this._country_id = value;
					this.SendPropertyChanged("country_id");
					this.Oncountry_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_country_description", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string country_description
		{
			get
			{
				return this._country_description;
			}
			set
			{
				if ((this._country_description != value))
				{
					this.Oncountry_descriptionChanging(value);
					this.SendPropertyChanging();
					this._country_description = value;
					this.SendPropertyChanged("country_description");
					this.Oncountry_descriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_active", DbType="Bit")]
		public System.Nullable<bool> active
		{
			get
			{
				return this._active;
			}
			set
			{
				if ((this._active != value))
				{
					this.OnactiveChanging(value);
					this.SendPropertyChanging();
					this._active = value;
					this.SendPropertyChanged("active");
					this.OnactiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_ts", DbType="DateTime")]
		public System.Nullable<System.DateTime> create_ts
		{
			get
			{
				return this._create_ts;
			}
			set
			{
				if ((this._create_ts != value))
				{
					this.Oncreate_tsChanging(value);
					this.SendPropertyChanging();
					this._create_ts = value;
					this.SendPropertyChanged("create_ts");
					this.Oncreate_tsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_update_ts", DbType="DateTime")]
		public System.Nullable<System.DateTime> update_ts
		{
			get
			{
				return this._update_ts;
			}
			set
			{
				if ((this._update_ts != value))
				{
					this.Onupdate_tsChanging(value);
					this.SendPropertyChanging();
					this._update_ts = value;
					this.SendPropertyChanged("update_ts");
					this.Onupdate_tsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="country_campaign", Storage="_campaigns", ThisKey="country_id", OtherKey="country_id")]
		public EntitySet<campaign> campaigns
		{
			get
			{
				return this._campaigns;
			}
			set
			{
				this._campaigns.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_campaigns(campaign entity)
		{
			this.SendPropertyChanging();
			entity.country = this;
		}
		
		private void detach_campaigns(campaign entity)
		{
			this.SendPropertyChanging();
			entity.country = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.territory")]
	public partial class territory : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _territory_id;
		
		private string _territory_description;
		
		private System.Nullable<bool> _active;
		
		private System.Nullable<System.DateTime> _create_ts;
		
		private System.Nullable<System.DateTime> _update_ts;
		
		private EntitySet<campaign> _campaigns;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onterritory_idChanging(int value);
    partial void Onterritory_idChanged();
    partial void Onterritory_descriptionChanging(string value);
    partial void Onterritory_descriptionChanged();
    partial void OnactiveChanging(System.Nullable<bool> value);
    partial void OnactiveChanged();
    partial void Oncreate_tsChanging(System.Nullable<System.DateTime> value);
    partial void Oncreate_tsChanged();
    partial void Onupdate_tsChanging(System.Nullable<System.DateTime> value);
    partial void Onupdate_tsChanged();
    #endregion
		
		public territory()
		{
			this._campaigns = new EntitySet<campaign>(new Action<campaign>(this.attach_campaigns), new Action<campaign>(this.detach_campaigns));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_territory_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int territory_id
		{
			get
			{
				return this._territory_id;
			}
			set
			{
				if ((this._territory_id != value))
				{
					this.Onterritory_idChanging(value);
					this.SendPropertyChanging();
					this._territory_id = value;
					this.SendPropertyChanged("territory_id");
					this.Onterritory_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_territory_description", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string territory_description
		{
			get
			{
				return this._territory_description;
			}
			set
			{
				if ((this._territory_description != value))
				{
					this.Onterritory_descriptionChanging(value);
					this.SendPropertyChanging();
					this._territory_description = value;
					this.SendPropertyChanged("territory_description");
					this.Onterritory_descriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_active", DbType="Bit")]
		public System.Nullable<bool> active
		{
			get
			{
				return this._active;
			}
			set
			{
				if ((this._active != value))
				{
					this.OnactiveChanging(value);
					this.SendPropertyChanging();
					this._active = value;
					this.SendPropertyChanged("active");
					this.OnactiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_ts", DbType="DateTime")]
		public System.Nullable<System.DateTime> create_ts
		{
			get
			{
				return this._create_ts;
			}
			set
			{
				if ((this._create_ts != value))
				{
					this.Oncreate_tsChanging(value);
					this.SendPropertyChanging();
					this._create_ts = value;
					this.SendPropertyChanged("create_ts");
					this.Oncreate_tsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_update_ts", DbType="DateTime")]
		public System.Nullable<System.DateTime> update_ts
		{
			get
			{
				return this._update_ts;
			}
			set
			{
				if ((this._update_ts != value))
				{
					this.Onupdate_tsChanging(value);
					this.SendPropertyChanging();
					this._update_ts = value;
					this.SendPropertyChanged("update_ts");
					this.Onupdate_tsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="territory_campaign", Storage="_campaigns", ThisKey="territory_id", OtherKey="territory_id")]
		public EntitySet<campaign> campaigns
		{
			get
			{
				return this._campaigns;
			}
			set
			{
				this._campaigns.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_campaigns(campaign entity)
		{
			this.SendPropertyChanging();
			entity.territory = this;
		}
		
		private void detach_campaigns(campaign entity)
		{
			this.SendPropertyChanging();
			entity.territory = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.usage")]
	public partial class usage : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _usage_id;
		
		private string _username;
		
		private int _usage_type_id;
		
		private System.Nullable<bool> _active;
		
		private System.Nullable<System.DateTime> _create_ts;
		
		private System.Nullable<System.DateTime> _update_ts;
		
		private EntityRef<usage_type> _usage_type;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onusage_idChanging(int value);
    partial void Onusage_idChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void Onusage_type_idChanging(int value);
    partial void Onusage_type_idChanged();
    partial void OnactiveChanging(System.Nullable<bool> value);
    partial void OnactiveChanged();
    partial void Oncreate_tsChanging(System.Nullable<System.DateTime> value);
    partial void Oncreate_tsChanged();
    partial void Onupdate_tsChanging(System.Nullable<System.DateTime> value);
    partial void Onupdate_tsChanged();
    #endregion
		
		public usage()
		{
			this._usage_type = default(EntityRef<usage_type>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usage_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int usage_id
		{
			get
			{
				return this._usage_id;
			}
			set
			{
				if ((this._usage_id != value))
				{
					this.Onusage_idChanging(value);
					this.SendPropertyChanging();
					this._usage_id = value;
					this.SendPropertyChanged("usage_id");
					this.Onusage_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usage_type_id", DbType="Int NOT NULL")]
		public int usage_type_id
		{
			get
			{
				return this._usage_type_id;
			}
			set
			{
				if ((this._usage_type_id != value))
				{
					if (this._usage_type.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onusage_type_idChanging(value);
					this.SendPropertyChanging();
					this._usage_type_id = value;
					this.SendPropertyChanged("usage_type_id");
					this.Onusage_type_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_active", DbType="Bit")]
		public System.Nullable<bool> active
		{
			get
			{
				return this._active;
			}
			set
			{
				if ((this._active != value))
				{
					this.OnactiveChanging(value);
					this.SendPropertyChanging();
					this._active = value;
					this.SendPropertyChanged("active");
					this.OnactiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_ts", DbType="DateTime")]
		public System.Nullable<System.DateTime> create_ts
		{
			get
			{
				return this._create_ts;
			}
			set
			{
				if ((this._create_ts != value))
				{
					this.Oncreate_tsChanging(value);
					this.SendPropertyChanging();
					this._create_ts = value;
					this.SendPropertyChanged("create_ts");
					this.Oncreate_tsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_update_ts", DbType="DateTime")]
		public System.Nullable<System.DateTime> update_ts
		{
			get
			{
				return this._update_ts;
			}
			set
			{
				if ((this._update_ts != value))
				{
					this.Onupdate_tsChanging(value);
					this.SendPropertyChanging();
					this._update_ts = value;
					this.SendPropertyChanged("update_ts");
					this.Onupdate_tsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="usage_type_usage", Storage="_usage_type", ThisKey="usage_type_id", OtherKey="usage_type_id", IsForeignKey=true)]
		public usage_type usage_type
		{
			get
			{
				return this._usage_type.Entity;
			}
			set
			{
				usage_type previousValue = this._usage_type.Entity;
				if (((previousValue != value) 
							|| (this._usage_type.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._usage_type.Entity = null;
						previousValue.usages.Remove(this);
					}
					this._usage_type.Entity = value;
					if ((value != null))
					{
						value.usages.Add(this);
						this._usage_type_id = value.usage_type_id;
					}
					else
					{
						this._usage_type_id = default(int);
					}
					this.SendPropertyChanged("usage_type");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.usage_type")]
	public partial class usage_type : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _usage_type_id;
		
		private string _usage_type_description;
		
		private System.Nullable<bool> _active;
		
		private System.Nullable<System.DateTime> _create_ts;
		
		private System.Nullable<System.DateTime> _update_ts;
		
		private EntitySet<usage> _usages;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onusage_type_idChanging(int value);
    partial void Onusage_type_idChanged();
    partial void Onusage_type_descriptionChanging(string value);
    partial void Onusage_type_descriptionChanged();
    partial void OnactiveChanging(System.Nullable<bool> value);
    partial void OnactiveChanged();
    partial void Oncreate_tsChanging(System.Nullable<System.DateTime> value);
    partial void Oncreate_tsChanged();
    partial void Onupdate_tsChanging(System.Nullable<System.DateTime> value);
    partial void Onupdate_tsChanged();
    #endregion
		
		public usage_type()
		{
			this._usages = new EntitySet<usage>(new Action<usage>(this.attach_usages), new Action<usage>(this.detach_usages));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usage_type_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int usage_type_id
		{
			get
			{
				return this._usage_type_id;
			}
			set
			{
				if ((this._usage_type_id != value))
				{
					this.Onusage_type_idChanging(value);
					this.SendPropertyChanging();
					this._usage_type_id = value;
					this.SendPropertyChanged("usage_type_id");
					this.Onusage_type_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usage_type_description", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string usage_type_description
		{
			get
			{
				return this._usage_type_description;
			}
			set
			{
				if ((this._usage_type_description != value))
				{
					this.Onusage_type_descriptionChanging(value);
					this.SendPropertyChanging();
					this._usage_type_description = value;
					this.SendPropertyChanged("usage_type_description");
					this.Onusage_type_descriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_active", DbType="Bit")]
		public System.Nullable<bool> active
		{
			get
			{
				return this._active;
			}
			set
			{
				if ((this._active != value))
				{
					this.OnactiveChanging(value);
					this.SendPropertyChanging();
					this._active = value;
					this.SendPropertyChanged("active");
					this.OnactiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_ts", DbType="DateTime")]
		public System.Nullable<System.DateTime> create_ts
		{
			get
			{
				return this._create_ts;
			}
			set
			{
				if ((this._create_ts != value))
				{
					this.Oncreate_tsChanging(value);
					this.SendPropertyChanging();
					this._create_ts = value;
					this.SendPropertyChanged("create_ts");
					this.Oncreate_tsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_update_ts", DbType="DateTime")]
		public System.Nullable<System.DateTime> update_ts
		{
			get
			{
				return this._update_ts;
			}
			set
			{
				if ((this._update_ts != value))
				{
					this.Onupdate_tsChanging(value);
					this.SendPropertyChanging();
					this._update_ts = value;
					this.SendPropertyChanged("update_ts");
					this.Onupdate_tsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="usage_type_usage", Storage="_usages", ThisKey="usage_type_id", OtherKey="usage_type_id")]
		public EntitySet<usage> usages
		{
			get
			{
				return this._usages;
			}
			set
			{
				this._usages.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_usages(usage entity)
		{
			this.SendPropertyChanging();
			entity.usage_type = this;
		}
		
		private void detach_usages(usage entity)
		{
			this.SendPropertyChanging();
			entity.usage_type = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.campaign_type")]
	public partial class campaign_type : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _campaign_type_id;
		
		private string _campaign_type_description;
		
		private int _list_order;
		
		private System.Nullable<bool> _active;
		
		private System.Nullable<System.DateTime> _create_ts;
		
		private System.Nullable<System.DateTime> _update_ts;
		
		private EntitySet<campaign> _campaigns;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncampaign_type_idChanging(int value);
    partial void Oncampaign_type_idChanged();
    partial void Oncampaign_type_descriptionChanging(string value);
    partial void Oncampaign_type_descriptionChanged();
    partial void Onlist_orderChanging(int value);
    partial void Onlist_orderChanged();
    partial void OnactiveChanging(System.Nullable<bool> value);
    partial void OnactiveChanged();
    partial void Oncreate_tsChanging(System.Nullable<System.DateTime> value);
    partial void Oncreate_tsChanged();
    partial void Onupdate_tsChanging(System.Nullable<System.DateTime> value);
    partial void Onupdate_tsChanged();
    #endregion
		
		public campaign_type()
		{
			this._campaigns = new EntitySet<campaign>(new Action<campaign>(this.attach_campaigns), new Action<campaign>(this.detach_campaigns));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_campaign_type_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int campaign_type_id
		{
			get
			{
				return this._campaign_type_id;
			}
			set
			{
				if ((this._campaign_type_id != value))
				{
					this.Oncampaign_type_idChanging(value);
					this.SendPropertyChanging();
					this._campaign_type_id = value;
					this.SendPropertyChanged("campaign_type_id");
					this.Oncampaign_type_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_campaign_type_description", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string campaign_type_description
		{
			get
			{
				return this._campaign_type_description;
			}
			set
			{
				if ((this._campaign_type_description != value))
				{
					this.Oncampaign_type_descriptionChanging(value);
					this.SendPropertyChanging();
					this._campaign_type_description = value;
					this.SendPropertyChanged("campaign_type_description");
					this.Oncampaign_type_descriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_list_order", DbType="Int NOT NULL")]
		public int list_order
		{
			get
			{
				return this._list_order;
			}
			set
			{
				if ((this._list_order != value))
				{
					this.Onlist_orderChanging(value);
					this.SendPropertyChanging();
					this._list_order = value;
					this.SendPropertyChanged("list_order");
					this.Onlist_orderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_active", DbType="Bit")]
		public System.Nullable<bool> active
		{
			get
			{
				return this._active;
			}
			set
			{
				if ((this._active != value))
				{
					this.OnactiveChanging(value);
					this.SendPropertyChanging();
					this._active = value;
					this.SendPropertyChanged("active");
					this.OnactiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_ts", DbType="DateTime")]
		public System.Nullable<System.DateTime> create_ts
		{
			get
			{
				return this._create_ts;
			}
			set
			{
				if ((this._create_ts != value))
				{
					this.Oncreate_tsChanging(value);
					this.SendPropertyChanging();
					this._create_ts = value;
					this.SendPropertyChanged("create_ts");
					this.Oncreate_tsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_update_ts", DbType="DateTime")]
		public System.Nullable<System.DateTime> update_ts
		{
			get
			{
				return this._update_ts;
			}
			set
			{
				if ((this._update_ts != value))
				{
					this.Onupdate_tsChanging(value);
					this.SendPropertyChanging();
					this._update_ts = value;
					this.SendPropertyChanged("update_ts");
					this.Onupdate_tsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="campaign_type_campaign", Storage="_campaigns", ThisKey="campaign_type_id", OtherKey="campaign_type_id")]
		public EntitySet<campaign> campaigns
		{
			get
			{
				return this._campaigns;
			}
			set
			{
				this._campaigns.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_campaigns(campaign entity)
		{
			this.SendPropertyChanging();
			entity.campaign_type = this;
		}
		
		private void detach_campaigns(campaign entity)
		{
			this.SendPropertyChanging();
			entity.campaign_type = null;
		}
	}
	
	public partial class usage_reportResult
	{
		
		private string _username;
		
		private string _country;
		
		private System.Nullable<System.DateTime> _last_entry;
		
		private System.Nullable<int> _entry_count;
		
		public usage_reportResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this._username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_country", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string country
		{
			get
			{
				return this._country;
			}
			set
			{
				if ((this._country != value))
				{
					this._country = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_entry", DbType="DateTime")]
		public System.Nullable<System.DateTime> last_entry
		{
			get
			{
				return this._last_entry;
			}
			set
			{
				if ((this._last_entry != value))
				{
					this._last_entry = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_entry_count", DbType="Int")]
		public System.Nullable<int> entry_count
		{
			get
			{
				return this._entry_count;
			}
			set
			{
				if ((this._entry_count != value))
				{
					this._entry_count = value;
				}
			}
		}
	}
	
	public partial class statistics_brands_reportResult
	{
		
		private string _description;
		
		private System.Nullable<int> _upload_count;
		
		public statistics_brands_reportResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this._description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_upload_count", DbType="Int")]
		public System.Nullable<int> upload_count
		{
			get
			{
				return this._upload_count;
			}
			set
			{
				if ((this._upload_count != value))
				{
					this._upload_count = value;
				}
			}
		}
	}
	
	public partial class statistics_campaign_types_reportResult
	{
		
		private string _description;
		
		private System.Nullable<int> _upload_count;
		
		public statistics_campaign_types_reportResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this._description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_upload_count", DbType="Int")]
		public System.Nullable<int> upload_count
		{
			get
			{
				return this._upload_count;
			}
			set
			{
				if ((this._upload_count != value))
				{
					this._upload_count = value;
				}
			}
		}
	}
	
	public partial class statistics_categories_reportResult
	{
		
		private string _description;
		
		private System.Nullable<int> _upload_count;
		
		public statistics_categories_reportResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this._description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_upload_count", DbType="Int")]
		public System.Nullable<int> upload_count
		{
			get
			{
				return this._upload_count;
			}
			set
			{
				if ((this._upload_count != value))
				{
					this._upload_count = value;
				}
			}
		}
	}
	
	public partial class statistics_countries_reportResult
	{
		
		private string _description;
		
		private System.Nullable<int> _upload_count;
		
		public statistics_countries_reportResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this._description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_upload_count", DbType="Int")]
		public System.Nullable<int> upload_count
		{
			get
			{
				return this._upload_count;
			}
			set
			{
				if ((this._upload_count != value))
				{
					this._upload_count = value;
				}
			}
		}
	}
	
	public partial class statistics_territories_reportResult
	{
		
		private string _description;
		
		private System.Nullable<int> _upload_count;
		
		public statistics_territories_reportResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this._description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_upload_count", DbType="Int")]
		public System.Nullable<int> upload_count
		{
			get
			{
				return this._upload_count;
			}
			set
			{
				if ((this._upload_count != value))
				{
					this._upload_count = value;
				}
			}
		}
	}
	
	public partial class upload_reportResult
	{
		
		private string _username;
		
		private string _country;
		
		private System.Nullable<int> _upload_count;
		
		public upload_reportResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this._username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_country", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string country
		{
			get
			{
				return this._country;
			}
			set
			{
				if ((this._country != value))
				{
					this._country = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_upload_count", DbType="Int")]
		public System.Nullable<int> upload_count
		{
			get
			{
				return this._upload_count;
			}
			set
			{
				if ((this._upload_count != value))
				{
					this._upload_count = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
